### ISSUE TITLE
Please help me in Preparation

### ISSUE THREAD

**Issue by Ankitmou** [solygambas/html-css-javascript-projects#1]

**Comment by solygambas** [comment]
hi @Ankitmou, can you be more specific?

**Comment by Ankitmou** [comment]
To do project 
I have learnt Html, HTML5, css, c++,

**Comment by solygambas** [comment]
well, that's more enough to start building stuff on your own! go ahead @Ankitmou!

**Comment by Ankitmou** [comment]
But I think I can do frontend so best lang to learn backend for this project

**Comment by solygambas** [comment]
I'm sorry but your question is not related to this repo alas, use [developer roadmaps](https://github.com/kamranahmedse/developer-roadmap) if you need to find your own path. If you know JavaScript, Node.js is a good choice for your backend.
