### ISSUE TITLE
Text overflows the panel when images shrink in Expanding Cards layout

### ISSUE THREAD

**Issue by vaishnavi4277** [solygambas/html-css-javascript-projects#37]
### Issue Title:
Text overflows the panel when images shrink in the Expanding Cards layout

### Description:
When the panels shrink in the Expanding Cards layout, the text (`h3`) spills out of the image boundaries instead of remaining fixed within the panel.

### Screenshots:

![Screenshot 2024-12-17 194936](https://github.com/user-attachments/assets/8a507cd4-5f82-4661-bb94-e64714383241)

### Expected Behavior:
The h3 text should remain fully contained within the panel boundaries, regardless of its size.

### Actual Behavior:
The h3 text overflows outside of the panel, becoming misaligned with the shrinking panel layout.

### Proposed Solution:
```
.panel {
  overflow: hidden; 
}

.panel h3 {
  white-space: nowrap; 
  text-overflow: ellipsis;
  overflow: hidden; 
  position: absolute;
  bottom: 10px;
  left: 10px;
  margin: 0;
}
```

**Comment by solygambas** [comment]
Thank you, @vaishnavi4277 🥇 

The problem with the text overflowing the panel in the Expanding Cards layout has been resolved. Applying the CSS property `background-size: cover` to the panel effectively addresses the issue by ensuring the image remains properly scaled within the panel, even when it shrinks.
