### ISSUE TITLE
047-testimonial box switcher

### ISSUE THREAD

**Issue by jbrown8484** [solygambas/html-css-javascript-projects#5]
I have a question re: this testimonial box project.

I have duplicated the code, exactly. However, only 2 of my 5 testimonials actually transition, and does not restart. It stops at the second testimonial, and just continuously reloads the second. The progress bar keeps rotating through, and you can see the second testimonial reload each time. But nothing else. It just seems to hang.

Is there an additional js that needs to be called for this to resolve? What am I missing?
[head]<br>
•project.css<br>
•fa-font all.css<br>
[/head]<br>
[body]<br>
•project html<br>
•async : project.js<br>
[/body]

Demo Link:
https://www.millerweisbrod.com/demo/Clay/Test/testimonial.html

**Comment by solygambas** [comment]
hi there, it's not exactly the same code, you need a role class somewhere:
<p class="role">Marketing</p>
otherwise this JS line can't work:
role.innerHTML = position

take care.

**Comment by jbrown8484** [comment]
Perfect! thanks for the assist. Have a good one.
